version: "3.8"
services:
  pgsql:
    container_name: pgsql
    image: postgres:15
    env_file:
      - ./apps/pgsql/.env
    volumes:
      - ./apps/pgsql/data:/data
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ruha -d vtb"]
      interval: 30s
      timeout: 30s
      retries: 3

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-api
    container_name: ${PROJECT_NAME}-api
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app
    ports:
      - 9000:9000
    healthcheck:
      test: curl http://api-partner:9000/healthcheck || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/nginx/www:/www
      # - ./apps/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/nginx/conf.nossl.d/:/etc/nginx/conf.d/
      - ./apps/certbot/conf:/etc/letsencrypt
      - ./apps/certbot/www:/var/www/certbot
      - ./apps/media/:/www/media/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"' && sed -e '/^http {/,/^}/{/^}/i\\client_max_body_size 0;' -e '}' /etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 30s
      retries: 10

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./apps/certbot/conf:/etc/letsencrypt
      - ./apps/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 5d & wait $${!}; done;'"
    depends_on:
      nginx:
        condition: service_healthy
