version: "3.8"
services:
  pgsql:
    container_name: ${PROJECT_NAME}-pgsql
    image: postgres:15
    env_file:
      - ./apps/pgsql/.env
    volumes:
      - ./apps/pgsql/data:/data
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ruha -d vtb"]
      interval: 30s
      timeout: 30s
      retries: 3

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}-api
    container_name: ${PROJECT_NAME}-api
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app
    ports:
      - 9000:9000
    healthcheck:
      test: curl http://api-partner:9000/healthcheck || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
