name: Android Build APK
env:
  main_project_module: apps/android
  playstore_name: VTBOnMap
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: cd apps/android && chmod +x ./gradlew
      - name: Run gradle tests
        run: cd apps/android && ./gradlew test
      - name: Build gradle project
        run: cd apps/android && ./gradlew build
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: cd apps/android && ./gradlew assembleDebug
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: cd apps/android && ./gradlew assemble
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: cd apps/android && ./gradlew ${{ env.main_project_module }}:bundleRelease
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
