name: Android Build APK
env:
  main_project_module: app
  android_path: apps/android
  playstore_name: VTBOnMap
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./${{ env.android_path }}/gradlew
      - name: Create local
        working-directory: ./${{ env.android_path }}
        run: echo MAPKIT_API_KEY=${{ secrets.YM_TOKEN }} >  local.properties
      - name: Run gradle tests
        working-directory: ./${{ env.android_path }}
        run: ./gradlew test
      - name: Build gradle project
        working-directory: ./${{ env.android_path }}
        run: ./${{ env.android_path }}/gradlew build
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        working-directory: ./${{ env.android_path }}
        run: ./${{ env.android_path }}/gradlew assembleDebug
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        working-directory: ./${{ env.android_path }}
        run: ./${{ env.android_path }}/gradlew assemble
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        working-directory: ./${{ env.android_path }}
        run: ./${{ env.android_path }}/gradlew ${{ env.main_project_module }}:bundleRelease
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          working-directory: ./${{ env.android_path }}
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          working-directory: ./${{ env.android_path }}
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          working-directory: ./${{ env.android_path }}
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
